### ISSUE TITLE
Add a good description for Repo

### ISSUE THREAD

**Issue by piyushgarg-dev** [piyushgarg-dev/P2PShare#5]
Please add a good description in README.MD file.

**Comment by brin188** [comment]
what kind of desc you want

**Comment by MaratheHarshad** [comment]
What kind of description you want ?

**Comment by BRajesh1995** [comment]
What type of description you want

**Comment by Anzala09** [comment]
What kind of description you want

**Comment by ronijames008** [comment]
What kind of desc you want?

**Comment by dheerus10** [comment]
what kind of description do you want

**Comment by gmgeetharanjani** [comment]
what kind of description is expected?

**Comment by udit8** [comment]
What kind of description you want?

**Comment by piyushgarg-dev** [comment]
Just add Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis fringilla enim egestas vehicula convallis. Sed lobortis convallis sem ac sodales. Donec sollicitudin ornare orci, ac pharetra ipsum convallis vitae. Suspendisse placerat nisl tortor, vel ornare neque ultricies sed. Donec vehicula lacus nisi, ac tempus velit placerat sit amet. Duis cursus purus at enim blandit consequat. Sed accumsan suscipit nunc, non porttitor purus ultrices ut. Morbi eget mattis neque. Integer eu est at ante tristique laoreet in a ex. Sed vehicula leo nibh, et cursus arcu vestibulum id. Donec ut est tincidunt, ultrices lorem vitae, iaculis ante. Phasellus volutpat nunc tincidunt mi volutpat interdum quis et ex.

**Comment by karthickm98** [comment]
Did you meet elon musk in dashboard

**Comment by ShikharSingh-GitHub** [comment]
i want to solve it

**Comment by hiitsakash** [comment]
What description you want??
